name: ds_salary_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2
  - scikit-learn=1.4
  - matplotlib
  - seaborn
  - jupyter
  - pip

  - pip:
      - xgboost
      - lightgbm
      - pyarrow